import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pixema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-slate-800">
        <main className="flex relative">
          <div className=" mr-20">
            <Sidebar />
          </div>
          <div className="w-full">
            <div className=" mb-10">
              <Footer />
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
